title: Rock Canyon Utah
description: > # this means to ignore newlines until "baseurl:"
  Rock Canyon Preservation Alliance in Provo, Utah
baseurl: "/rockcanyonutah"
# url: "http://rockcanyonutah.com"
url: "https://canadaduane.github.io"

gacode: "UA-85522875-1"

source: "."
destination: "_site"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

include:
  - install.sh

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Navigation for menu links
navigation:
 - text: Home
   url: /
 - text: Directions
   url: /#link-directions
 - text: Canyon Hikes &amp; Maps
   url: /hikes/
 - text: Climbing Corner
   url: /climbing/
 - text: Identify Canyon Nature
   url: /nature/
 - text: Geology
   url: /geology/
 - text: Canyon History
   url: /history/
